### ISSUE TITLE
NuGet packages don't have tags and rider refuses to install them

### ISSUE THREAD

**Issue by NIMFER** [StirlingLabs/MsQuic.Net#17]
Hey, so while attempting to install the NuGet packages in my project I got the following error:

 `
Could not install package 'StirlingLabs.MsQuic.Bindings.runtime.linux-x64.openssl 2.1.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

judging by the error, I'd say that those packages refuse to install due to them not having proper tags, here is a list of packages with that issue:

- https://www.nuget.org/packages/StirlingLabs.MsQuic.Bindings.runtime.linux-x64.openssl
- https://www.nuget.org/packages/StirlingLabs.MsQuic.Bindings.runtime.win-x64.openssl
- https://www.nuget.org/packages/StirlingLabs.MsQuic.Bindings.runtime.osx.openssl
- https://www.nuget.org/packages/StirlingLabs.MsQuic.Bindings.runtime.win-x64

**Comment by NIMFER** [comment]
just wanted to add that other packages can be installed without any issues if I enable dependency ignoring

**Comment by TYoungSL** [comment]
Can you try using the command line without Rider, and/or Visual Studio, VSCode as well?

I don't think we don't directly support the .NET Framework v4.x, though if this is an issue with a .NET Standard project or other, we can troubleshoot further.

We'll see about marking them as netstandard2.0/2.1 and net6.0.

**Comment by Rjvs** [comment]
@NIMFER latest versions have added tags for netstandard2.0 & 2.1 LMK if that helps you.
