### ISSUE TITLE
Delegate `OnShutdown` does not match call argument types

### ISSUE THREAD

**Issue by TheDeadCode** [StirlingLabs/MsQuic.Net#5]
[QuicPeerConnection.cs#L790](https://github.com/StirlingLabs/MsQuic.Net/blob/main/StirlingLabs.MsQuic/QuicPeerConnection.cs#L790)

Declared as `public event EventHandler<QuicPeerConnection, bool, bool>? ConnectionShutdown` but called as `EventHandler<QuicPeerConnection, ulong, bool, bool>` on [QuicPeerConnection.cs#L811](https://github.com/StirlingLabs/MsQuic.Net/blob/main/StirlingLabs.MsQuic/QuicPeerConnection.cs#L811) and [QuicPeerConnection.cs#L835](https://github.com/StirlingLabs/MsQuic.Net/blob/main/StirlingLabs.MsQuic/QuicPeerConnection.cs#L835)

**Comment by TYoungSL** [comment]
Friday most likely.
